### ISSUE TITLE
Input to reshape is a tensor with 12288 values, but the requested shape has 49152

### ISSUE THREAD

**Issue by deep-unlearn** [khanrc/tf.gans-comparison#5]
Hello,

I am trying to run the BEGAN model but I am keep getting an error'

'Input to reshape is a tensor with 12288 values, but the requested shape has 49152'.

Obviously this has to do with sizes as 12288 = (64,64,3) and 49152=(128,128,3). 
Tried to find the error but I cannot locate it. Any ideas ?

I guess the covert script by default reshapes inputs to (64,64,3)

**Comment by khanrc** [comment]
It doesn't matter actually, because the images are resized into (64, 64) through input pipeline. Check the code in `inputpipe.py`, `read_parse_preproc()` func, 21th line.

**Comment by khanrc** [comment]
While updating, I did not test all the code works well for every updates. So, If your code is not up to date, use the latest version. If you have the latest version, please let me know. I will test it.

**Comment by deep-unlearn** [comment]
Hello, thanks for the quick reply. I guess I am using the latest version cause I cloned your code 2 days ago. Did you made any major changes in the meantime ?

**Comment by deep-unlearn** [comment]
Ok I think I found the problem. The input is of (64,64) in your `convert.py` script. However in `inputpipe.py` in line 20 you define the input as (128,128).

I changed this line (20) and now it works. Modified to:

`tf.reshape(image, [64, 64, 3])`

**Comment by khanrc** [comment]
I am glad to find the problem :) `convert.py` should be modified appropriately before used. I should update the code and readme more kindly...
