### ISSUE TITLE
ModuleNotFoundError: No module named 'basemodel'

### ISSUE THREAD

**Issue by sumorday** [khanrc/tf.gans-comparison#8]
in dcgan.py.
from basemodel import BaseModel

When I run 
python train.py --help

ModuleNotFoundError: No module named 'basemodel'

**Comment by Shan2L** [comment]
> in dcgan.py. from basemodel import BaseModel
> 
> When I run python train.py --help
> 
> ModuleNotFoundError: No module named 'basemodel'

Just replace the code in each file like follows
origin:
`
 from basemodel import BaseModel
`
new:
`
from models.basemodel import BaseModel
`
That works.

**Comment by sumorday** [comment]
> 
Thank you so much. 
But I have another question. If I want to correct the loss function like dcgan and sngan or other gans.
should I do this in the net of GAN.py? (Because I found all the models were came from the original models GAN.)

**Comment by Shan2L** [comment]
In fact, I don't know what do you mean by   'correct the loss function'. 
If you want to modify the loss function of any GAN, you may edit the function `_build_train_graph`   within their class.
